---
- name: Install nginx
  action: apt pkg={{ item }} state=latest
  sudo: yes
  with_items:
      - nginx

- name: Copy nginx config
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  sudo: yes

- name: Copy virtual host config
  template: src=default.conf.j2 dest=/etc/nginx/sites-available/{{ server_name }}.conf
  sudo: yes

- name: Create symlink.
  sudo: yes
  file: state=link src=/etc/nginx/sites-available/{{ server_name }}.conf path=/etc/nginx/sites-enabled/{{ server_name }}.conf

- name: Reload nginx
  sudo: yes
  service: name=nginx state=reloaded