---
- name: Changing perm of "/var/www/update.sh", adding "+x"
  file: dest=/var/www/update.sh mode=a+x

- command: ./update.sh
  args:
    chdir: /var/www/
  register: hello

- debug: msg="{{ hello.stdout }}"
