---
- name: Check if composer exists.
  sudo: yes
  stat: path=/usr/local/bin/composer
  register: composer_file

- name: Install Composer
  sudo: yes
  shell: >
      curl -sS https://getcomposer.org/installer | sudo php7.1 -- --install-dir=/usr/local/bin --filename=composer
  when: composer_file.stat.exists == false

- name: Update composer if already exists.
  sudo: yes
  shell: >
      composer selfupdate
  when: composer_file.stat.exists == true
