---
# This playbook contains common plays that will be run on all nodes.

- name: update apt
  action: command /usr/bin/apt-get update
  sudo: yes

- name: install python-software-properties
  action: apt pkg=python-software-properties state=present
  sudo: yes

- name: install web server packages
  action: apt pkg={{item}} state=installed
  sudo: yes
  with_items:
    - curl
    - wget
    - zip
    - unzip
